[package]
name = "qberust-core"
version = "0.1.0"
authors = ["artblnd <junryoungju@gmail.com>"]
edition = "2018"

[lib]
path = "lib.rs"

[dependencies]
parking_lot = "0.11.2"
rand = "0.8.4"
thiserror = "1.0.30"